---
# For installing docker-compose, please refer page
# https://docs.docker.com/compose/install/
# For using docker compose
# 1. start docker container, like vagrant, go under folder
#    contains docker-compose.yml file and run:
#    $ docker-compose up -d
# 2. stop the container
#    $ docker-compose stop
# 3. remove the container
#    $ docker-compose rm -f

# TO attach inside conatainer
# $ docker exec -ti plotbot /bin/bash


shibboleth:
  container_name: shibboleth-idp
  image: jtgasper3/shibboleth-idp
  volumes:
    - ./configfiles:/external-mount

